version: '3.7'
services:
  api:
    build: .
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  db:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: