spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
        active: local

#  datasource:
#    driverClassName: org.h2.Driver

logging:
  file: logfile.log
  level:
    org.hibernate.SQL: DEBUG
