server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
#    hibernate:
#      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://10.5.23.19:5432/postgres
    username: postgres
    password: docker
    driverClassName: org.postgresql.Driver
logging:
 file: logfile.log
 level:
  root: ERROR
  org.springframework.web: DEBUG
  org.springframework: DEBUG
#  org.springframework.boot: ERROR
#  org.postgresql: ERROR
  org.hibernate: ERROR
